service: tesisFunct-azure-nodejs

provider:
  name: azure
  location: West US

plugins:
  - serverless-azure-functions

package:
  exclude:
    - node_modules/serverless-azure-functions/**
    - .gitignore
    - .git/**


functions:
##
# ================  Hello ================ #
##
  tesisFuncthello128:
    handler: handler.hello128
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          # End function
  tesisFuncthello256:
    handler: handler.hello256
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          # End function
  tesisFuncthello512:
    handler: handler.hello512
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          # End function
  tesisFuncthello1024:
    handler: handler.hello1024
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          # End function
  tesisFuncthello2048:
    handler: handler.hello2048
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          # End function
##
# ================  Fft ================ #
##
  tesisFunctfft128:
    handler: handler.fft128
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
  tesisFunctfft256:
    handler: handler.fft256
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          # End function
  tesisFunctfft512:
    handler: handler.fft512
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          # End function
  tesisFunctfft1024:
    handler: handler.fft1024
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          # End function
  tesisFunctfft2048:
    handler: handler.fft2048
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
          # End function