service: tesisFunct-azure-nodejs

provider:
  name: azure
  location: West US

plugins:
  - serverless-azure-functions

package:
  exclude:
    - node_modules

functions:
  tesisFuncthello128:
    handler: handler.hello128
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
  tesisFuncthello256:
    handler: handler.hello256
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
  tesisFuncthello512:
    handler: handler.hello512
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
  tesisFuncthello1024:
    handler: handler.hello1024
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
  tesisFuncthello2048:
    handler: handler.hello2048
    events:
      - http: true
        x-azure-settings:
          authLevel : anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: res
    

# The following are a few examples of other events you can configure:
#
# events:
#   - queue: YourQueueName
#     x-azure-settings:
#       connection : StorageAppSettingName
#   - blob:
#     x-azure-settings:
#       name: bindingName
#       direction: in
