language: node_js
node_js: '8'
env:
  matrix:
  - PROVIDER=aws
  global:
  - secure: palRguGgl5IsYvW86ifg5gOtP4UQCv79n7Q3O8+K4mk3T7nmFf9laJ/3FV+eIUESFH+ohxVCla4q+/vsBBZQocGfbh9HJbaxjJm5J2giSGf2C1CfytBA5xOsMKMkLdZvOSoC/Fm7OXKEluatwTXfFgFHFV0AZwo6tSGZYjZqKZSgruAc8ugM8Rh9XK989RXyNmUB622VmhqULXuHw5y2uQER97tXgVlVOC9DJ5Lsk17yVgW1l/FHEC+hcHST4x/EujFwtGKbBTele7iIHan+Np4wRG3zDlyMmI90LhSu0HMK9Er0H2eV7sufk/y5WY0HHaJ4Cm0QbT6Ps5zMgj6iOMveuFyAWzkwA2MCvg4inXPv6wnh0NdEMNyonfXPyVSOO0+kJkpepFEvTidTdVByt4UgqnMpy+wImRvnf5ID5R7y8UpNldXbXXvpFTaUNS933iqZdjgCkBc4QMdrDqViTejxcDlX9mq1mpv68VNqoF/Lz6TFFcMk1CIW7fq/bq7qA3dyAdcHLNsAwdJkGJOlw+FssqJnmWsg6temPgLWJFeNQpUAKiLQe8knAcP0TQ+SKixP8MfPiGmHulCQTRchzVGNQT5ZXT29qnq5mL4CcuQmGiFzZ13qPmrPPu/94KrPWtTaYhE221tNgNtuyw8of9CEISar6ZJp2J6WbTUWIOQ=
  - secure: uRdKBQ+pQj/Fob061A5ZiU/PO0nkjVlrtdtAMeswCUoSnFIuNmDwU1rCWPj0OM5A3If30EaFSNRy57aHx4+hFKMelvSPY8nIW/Bu44jSqtnp9rrRX2dsS1fSYHb0XYJDaGJz5jMtFlbuWrW/L8mmeJ6oOfbqmxHorJfKF2ErMF9L96RIHB+osYegMxUiX88/+ULaVU7XVoXFaPOEggpmoFBfisGx74ynRBk70sxZdzCgN2gDb7uwvPlyQjbn6g5uNztgzhybs4U2Eb4H77WqLhnlDt2Og9MpURfEP7HtHpyH6dcSJvcVaweRnHGvdaTV/qaj6GKigVid4M+iKI9XUdUZqxOWYs7JIAzPifUjdlUTqIBPSweaWI1Cnef0wOkeuAy3c9u9vG00lsm67IfmJcjZJOeVhEdS5718E5mduXKzML7XVFvOXd8gItipHKR03+dKc5FwXWZAlY5qILoLr+UIlXIH3LTVIYSAQ7EvPbIk7gVB5N/CPm8SvExp1LruKYgLQy7Fzb0jne55jr2u/wemsFLrSofgMnwC7lyAgZsrmLBxEKTXprx8ShzesTjiaK4IjCDR9jRH/VLvNpy7Q06zpQKz7kqZaFXJplhqKYP5DZS31v4JptlPpHNr83Eh0PUp/jrkgRGXEOzF+QRkdGQ+y5hV7S1ITyGhCA4zwJA=
before_install:
- npm install -g serverless
script:
- cp functions $PROVIDER
- cd $PROVIDER
- sls deploy
