language: node_js
node_js: '8'
sudo: required

before_install:
- openssl aes-256-cbc -K $encrypted_73f9e7942726_key -iv $encrypted_73f9e7942726_iv
  -in key.json.enc -out key.json -d
- sudo apt-get install libsecret-1.dev
- npm update -g
- npm install -g serverless

env:
  - amazon
  - azure
  - ibm
  - google



matrix:
  - PROVIDER=amazon/node
  - PROVIDER=amazon/python
  # - PROVIDER=azure
  # - PROVIDER=google
  # - PROVIDER=ibm
script:
  - cp -R functions $PROVIDER/
  - cd $PROVIDER
  - npm i
  - sls deploy

cache:
  directories:
  - node_modules