service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10

package:
  exclude:
    - node_modules

functions:
  hello128:
    handler: handler.hello128
    events:
      - http:
          path: hello1
          method: get
    memorySize: 128

  hello256:
    handler: handler.hello256
    events:
      - http:
          path: hello2
          method: get
    memorySize: 256

  hello1512:
    handler: handler.hello512
    events:
      - http:
          path: hello3
          method: get
    memorySize: 512

  hello1024:
    handler: handler.hello1024
    events:
      - http:
          path: hello4
          method: get
    memorySize: 1024
    
  hello2048:
    handler: handler.hello2048
    events:
      - http:
          path: hello5
          method: get
    memorySize: 2048