service: openwhisk-python

provider:
  name: openwhisk
  runtime: python

package:
  exclude: 
    - node_modules
    - requirements.txt
    - Readme.md
    - .gitignore
    - package.json

plugins:
  - serverless-offline-python
  - serverless-python-requirements


custom:
  pythonRequirements:
    zip: true

functions:
  hello:
    handler: handler.hello
    annotations:
      web-export: true
    events:
      - http: GET /ml
    memory: 512

plugins:
  - serverless-openwhisk
