service: gcf-nodejs

provider:
  name: google
  runtime: nodejs
  project: tesis-gcl
  credentials: ../key.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  hello128:
    handler: hello128
    events:
      - http: path
    memorySize: 128
  hello256:
    handler: hello256
    events:
      - http: path
    memorySize: 256
  hello512:
    handler: hello512
    events:
      - http: path
    memorySize: 512
  hello1024:
    handler: hello1024
    events:
      - http: path
    memorySize: 1024
  hello2048:
    handler: hello2048
    events:
      - http: path
    memorySize: 2048
