service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10

package:
  exclude:
    - .gitignore
    - .git/**
    - package.json
    - "*.py"

functions:
##
# ================  Hello ================ #
##
  hello128:
    handler: handler.hello128
    events:
      - http:
          path: hello1
          method: get
    memorySize: 128
    # end function
  hello256:
    handler: handler.hello256
    events:
      - http:
          path: hello2
          method: get
    memorySize: 256
    # end function
  hello1512:
    handler: handler.hello512
    events:
      - http:
          path: hello3
          method: get
    memorySize: 512
    # end function
  hello1024:
    handler: handler.hello1024
    events:
      - http:
          path: hello4
          method: get
    memorySize: 1024
    # end function
  hello2048:
    handler: handler.hello2048
    events:
      - http:
          path: hello5
          method: get
    memorySize: 2048
    # end function
##
# ================  Fft ================ #
##
  fft128:
    handler: handler.fft128
    events:
      - http:
          path: fft1
          method: get
    memorySize: 128
    timeout: 540
    # end function
  fft256:
    handler: handler.fft256
    events:
      - http:
          path: fft2
          method: get
    memorySize: 256
    timeout: 540
    # end function
  fft512:
    handler: handler.fft512
    events:
      - http:
          path: fft3
          method: get
    memorySize: 512
    timeout: 540
    # end function
  fft1024:
    handler: handler.fft1024
    events:
      - http:
          path: fft4
          method: get
    memorySize: 1024
    timeout: 540
    # end function
  fft2048:
    handler: handler.fft2048
    events:
      - http:
          path: fft5
          method: get
    memorySize: 2048
    timeout: 540
    # end function